version: '3.8'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secr3t
      - POSTGRES_DB=db

  api:
    container_name: api
    restart: always
    build:
      context: app
      target: prod
    depends_on:
      - db

  front:
    build:
      context: front
      target: prod
    restart: unless-stopped
    depends_on:
      - api

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - api
      - front
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db:
